name: Android emulator

on: 
  workflow_dispatch:
    inputs: 
      tags: 
        description: image tag version
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android: [8.1, 10.0, 11.0, 12.0]
        tag: [v1.21.0.9]
    env:
      RELAXED_SECURITY: True
      DEFAULT_CAPABILITIES: '{"skipDeviceInitialization": false}'
      ANDROID_VERSION: ${{ matrix.android }}
      TRAVIS_TAG: ${{ github.event.inputs.tags }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: bash travis.sh
        run: bash travis.sh
        shell: bash
