name: Android emulator

on: 
  workflow_dispatch:
    inputs: 
      tags: 
        description: image tag version
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        android: [12.0, 14.0, 15.0, 16.0]
        tag: [v1.21.0.9]
    env:
      ANDROID_VERSION: ${{ matrix.android }}
      TRAVIS_TAG: ${{ github.event.inputs.tags }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: bash travis.sh
        run: bash travis.sh
        shell: bash
